### ISSUE TITLE
Methodes http de Express

### ISSUE THREAD

**Issue by MilanLachance** [polymtl-web/polymtl-web.github.io#1]
Dans la section Routing du tutoriel Express, au dernier paragraphe de la section C'est quoi le routing?, il est dit que: "Express nous offre une méthode pour chacun des verbes de HTTP : GET, PUT, DELETE". POST ne figure pas dans la liste et ca peut porter a croire que cette methode n'est pas supporte.

**Comment by antoinebeland** [comment]
Bonjour @MilanLachance! Effectivement, cela peut porter à confusion. Je vais faire la modification à l'instant. Merci pour la remarque.

**Comment by antoinebeland** [comment]
La modification a été apportée. Merci encore!

**Comment by antoinebeland** [comment]
La modification a été apportée. Merci encore!
